// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6f7DLaS2IG_P3FB_3hc4tEtdX1putAnQ',
    authDomain: 'getxdistil.firebaseapp.com',
    projectId: 'getxdistil',
    storageBucket: 'getxdistil.firebasestorage.app',
    messagingSenderId: '878087895723',
    appId: '1:878087895723:web:8d563e652a01b355c655ee',
    measurementId: 'G-14QYSD2WLE',
  );
}
